language: go
go:
- '1.13'

services:
  - docker

script:
- go vet ./...
- make test

before_deploy: |-
  if [ ! -f /tmp/tagged ]; then
    git config --local user.name "$USERNAME"
    git config --local user.email "$EMAIL"
    make release
    export TRAVIS_TAG=v$(grep "VERSION="  Makefile | cut -d= -f2)
    git tag $TRAVIS_TAG && touch /tmp/tagged
  fi

deploy:
  - provider: script
    script: make docker-release
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    api_key:
      secure: XHNw2KBxm9D9KxJUwqFk1IKVBkE8ma7VBgq4ZHVyNwg1pKGmkk0cURKDeVgJhdGyl7i3VRHzFurmYY0OmB9sBaheSp88y3okHyegFXXBFYk0Tt7Fk6D99rph8PP4ziK/99+8i9WuPe7R+GBeSkiqN4VMRGNdYJx6Q8t4+DxkS927Tw/JvYKPok2vHLT6fhtsl6zZEJBfHNRqqemPhma417BfmIl45DxbCieTAC9uWLFH6ViczsqJV6XPHHwpO4w2ROuFQYLmVz/bdvN6iVHJEmlsnNY0dFBWrGt30acIc+ydkalatdZG8ppXjebhio7KEPt1e85B3f9CK1x654SN3ZEc56ldvgenW3ckuqAOYq01gakbLDKUsB0lf0dDTXv/2koQ+aoErraQt3L+0XFvUMzSbsICzjhMu6Vf0GkH2sqXSWLHrBMp+nOuM9a6KBr1J7VXTVRQbPMSTJfm16pXJ4D9PZwlBzZsEkD/0JW8gpAPYjbrS8HRrxMQrYYclcvJX4o8CnE65Fm6Hgcowr5jp8k2SMLrXeBbVaCO2Y+OyKOADGl4IGcGO3hAK9wzCoBBSdbSf2Ix2g0tmkp0cj16QmH8p7l80zBLC28DIUdCS49przWCPNSKf3Cb11Slx/kw3il4uZBkpFdaK4AjNMfB+Z833nGbEI8esyumtrcE0oE=
    file_glob: true
    file: bin/*.*
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_EVENT_TYPE != cron
